In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('diabetes (2).csv')

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
df.SkinThickness.value_counts()

0     227
32     31
30     27
27     23
23     22
33     20
18     20
28     20
31     19
39     18
19     18
29     17
37     16
26     16
22     16
40     16
25     16
35     15
41     15
36     14
15     14
17     14
20     13
24     12
42     11
13     11
21     10
34      8
46      8
38      7
12      7
14      6
16      6
11      6
43      6
45      6
10      5
44      5
48      4
47      4
50      3
49      3
54      2
52      2
7       2
8       2
60      1
56      1
63      1
51      1
99      1
Name: SkinThickness, dtype: int64

In [6]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [7]:
def replace_zeros(column_name):
    mean = round(df[df[column_name]!= 0][column_name].mean(),0)
    df[column_name] = df[column_name].replace(0,mean)

In [8]:
for x in list(df)[1:-2]:
    print(x)

Glucose
BloodPressure
SkinThickness
Insulin
BMI
DiabetesPedigreeFunction

In [9]:
df_new = pd.read_csv('new_diabetes.csv')

In [10]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [11]:
df_new.drop(['Unnamed: 0'],1,inplace=True)

In [12]:
df_new.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.00000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,4.473958,121.451823,72.404948,29.24349,159.154948,32.497656,0.471876,33.324219,0.348958
std,3.348798,30.807562,12.706550,10.63275,118.160425,6.954240,0.331329,11.951023,0.476951
min,1.000000,44.000000,24.000000,7.00000,0.000000,18.200000,0.078000,21.000000,0.000000
25%,2.000000,99.000000,64.000000,21.00000,78.000000,27.475000,0.243750,24.000000,0.000000
50%,3.000000,116.000000,74.000000,30.00000,130.000000,32.400000,0.372500,29.000000,0.000000
75%,7.000000,141.000000,80.000000,36.25000,196.000000,36.800000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.00000,846.000000,67.100000,2.420000,81.000000,1.000000

In [13]:
df_new['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [14]:
from sklearn.feature_selection import RFE, SelectKBest, chi2, f_classif,SelectFromModel
import statsmodels.api as sm
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score
from sklearn.model_selection import cross_val_score, cross_val_predict, GridSearchCV, train_test_split as tts
from sklearn.preprocessing import StandardScaler

In [15]:
scalar = StandardScaler()

In [16]:
X = df_new.drop(['Outcome'],1)
y = df_new['Outcome']

In [17]:
X = pd.DataFrame(scalar.fit_transform(X),columns=list(X))

In [18]:
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.455995,0.862304,-0.031890,0.541747,-1.347817,0.158617,0.468492,1.396253
1,-1.038051,-1.183981,-0.504395,0.541747,-1.347817,-0.848619,-0.365061,-0.194605
2,1.053614,1.999129,-0.661897,0.541747,-1.347817,-1.323459,0.604397,-0.110876
3,-1.038051,-1.054058,-0.504395,-0.587577,-0.551770,-0.632783,-0.920763,-1.031899
4,-1.038051,0.505016,-2.551917,0.541747,0.074905,1.525581,5.484909,-1.031899

# Model 1  Normal Logistic Regression

In [19]:
log_reg = LogisticRegression()
X_train, X_test, y_train, y_test = tts(X, y, test_size = 0.3, random_state = 42)
log_reg.fit(X_train, y_train)
y_pred = log_reg.predict(X_test)
print(f'Accuracy Score : {accuracy_score(y_test, y_pred)}')
print(f'Confusion Matrix : {confusion_matrix(y_test, y_pred)}')
print(f'Classification Report: {classification_report(y_test, y_pred)}')

Accuracy Score : 0.7445887445887446
Confusion Matrix : [[124  27]
 [ 32  48]]
Classification Report:               precision    recall  f1-score   support

           0       0.79      0.82      0.81       151
           1       0.64      0.60      0.62        80

    accuracy                           0.74       231
   macro avg       0.72      0.71      0.71       231
weighted avg       0.74      0.74      0.74       231

C:\Users\Ajay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

# Model 2 RFE

In [20]:
ranking = log_reg.coef_.tolist()[0]

In [21]:
features = list(X)

In [22]:
d = dict(zip(features,ranking))

In [23]:
d= pd.DataFrame(d.items(), columns=["Features", "Ranking"])

In [24]:
d

                   Features   Ranking
0               Pregnancies  0.140273
1                   Glucose  1.117285
2             BloodPressure -0.170108
3             SkinThickness -0.043997
4                   Insulin  0.022983
5                       BMI  0.786709
6  DiabetesPedigreeFunction  0.105771
7                       Age  0.468746

In [25]:
d.sort_values(["Ranking"], ascending = False)

                   Features   Ranking
1                   Glucose  1.117285
5                       BMI  0.786709
7                       Age  0.468746
0               Pregnancies  0.140273
6  DiabetesPedigreeFunction  0.105771
4                   Insulin  0.022983
3             SkinThickness -0.043997
2             BloodPressure -0.170108

In [26]:
f1 = ["Glucose", "BMI", "Age"]

In [27]:
rfe = RFE(log_reg, 4)

In [28]:
rfe.fit(X,y)

C:\Users\Ajay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ajay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ajay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ajay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ajay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

RFE(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                 fit_intercept=True, intercept_scaling=1,
                                 l1_ratio=None, max_iter=100,
                                 multi_class='warn', n_jobs=None, penalty='l2',
                                 random_state=None, solver='warn', tol=0.0001,
                                 verbose=0, warm_start=False),
    n_features_to_select=4, step=1, verbose=0)

In [29]:
rfe.support_

array([ True,  True, False, False, False,  True,  True, False])

In [30]:
rfe.ranking_

array([1, 1, 3, 5, 4, 1, 1, 2])

In [31]:
features

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']

In [32]:
f2 = ['Pregnancies','Glucose','BMI','DiabetesPedigreeFunction']

# Model 3 : Backward Elimination

In [33]:
def backward_elimination(Y,X):
    cols = list(X.columns)
    while len(cols) > 0:
        p = []
        X_new = X[cols]
        X_new = sm.add_constant(X_new)
        model = sm.OLS(Y, X_new).fit()
        pvalues = pd.Series(model.pvalues.values[1:],index = cols)
        max_pvalues = max(pvalues)
        feature_with_max_pvalues = pvalues.idxmax()
        if max_pvalues > 0.05:
            cols.remove(feature_with_max_pvalues)
        else:
            return cols
            break

In [34]:
_X = df_new.drop(['Outcome'],1)
_y = df_new['Outcome']
_X = pd.DataFrame(scalar.fit_transform(X),columns=list(X))

In [35]:
feature_selected = backward_elimination(_y,_X)

C:\Users\Ajay\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

In [36]:
feature_selected

['Pregnancies', 'Glucose', 'BMI', 'DiabetesPedigreeFunction', 'Age']

# Model 4 : Kbest

#### Using Chi2

In [37]:
from sklearn.preprocessing import MinMaxScaler
Minmax = MinMaxScaler()
_X_b = df.drop('Outcome',1)
_y_b = df['Outcome']
#Standardscaler will not work because Kbest does not take -ve value
_X_b = pd.DataFrame(Minmax.fit_transform(_X_b), columns=list(_X_b))

In [38]:
_X_b.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.352941,0.743719,0.590164,0.353535,0.000000,0.500745,0.234415,0.483333
1,0.058824,0.427136,0.540984,0.292929,0.000000,0.396423,0.116567,0.166667
2,0.470588,0.919598,0.524590,0.000000,0.000000,0.347243,0.253629,0.183333
3,0.058824,0.447236,0.540984,0.232323,0.111111,0.418778,0.038002,0.000000
4,0.000000,0.688442,0.327869,0.353535,0.198582,0.642325,0.943638,0.200000

In [39]:
_y_b.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [40]:
features = list(_X_b)
features

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']

In [41]:
kbest = SelectKBest(chi2, k = 4)

In [42]:
fit = kbest.fit(_X_b,_y_b)

In [43]:
fit.pvalues_

array([0.01042974, 0.00773032, 0.70403691, 0.46390984, 0.10879832,
       0.16777946, 0.09673383, 0.00417592])

In [44]:
rankings = fit.scores_.tolist()

In [45]:
rankings

[6.559981802110764,
 7.094909751980554,
 0.14430633783049784,
 0.536444846831558,
 2.5715901571182176,
 1.9026727769156078,
 2.7585839144540985,
 8.20569066697144]

In [46]:
d = pd.DataFrame(dict(zip(features,rankings)).items(), columns={"Features","Ranking"})

In [47]:
d.sort_values(['Ranking'], ascending=False)

                   Features   Ranking
7                       Age  8.205691
1                   Glucose  7.094910
0               Pregnancies  6.559982
6  DiabetesPedigreeFunction  2.758584
4                   Insulin  2.571590
5                       BMI  1.902673
3             SkinThickness  0.536445
2             BloodPressure  0.144306

In [48]:
feature_4 = ['Glucose', 'Age', 'Pregnancies', 'DiabetesPedigreeFunction']

#### f_classif

In [49]:
kbest = SelectKBest(f_classif, k = 4)
fit = kbest.fit(X,y)
print(fit.pvalues_)
rankings = fit.scores_.tolist()
d = pd.DataFrame(dict(zip(features,rankings)).items(), columns={"Features","Ranking"})
d.sort_values(['Ranking'], ascending=False)

[6.68142273e-10 4.04408491e-48 1.07604723e-04 3.73936831e-06
 2.56095195e-05 8.69654854e-19 1.25460701e-06 7.35886163e-12]

                   Features     Ranking
1                   Glucose  244.992929
5                       BMI   82.536787
7                       Age   48.429255
0               Pregnancies   39.101595
6  DiabetesPedigreeFunction   23.871300
3             SkinThickness   21.709909
4                   Insulin   17.937047
2             BloodPressure   15.156127

In [50]:
features_5 = ['Glucose', 'BMI', "Pregnancies", 'Age']

Note : SelectKBest works on Statistical test to select features.
       RFE works on model to select features

# Model 6 : SelectFromModel

In [51]:
_X_b

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.352941,0.743719,0.590164,0.353535,0.000000,0.500745,0.234415,0.483333
1,0.058824,0.427136,0.540984,0.292929,0.000000,0.396423,0.116567,0.166667
2,0.470588,0.919598,0.524590,0.000000,0.000000,0.347243,0.253629,0.183333
3,0.058824,0.447236,0.540984,0.232323,0.111111,0.418778,0.038002,0.000000
4,0.000000,0.688442,0.327869,0.353535,0.198582,0.642325,0.943638,0.200000
5,0.294118,0.582915,0.606557,0.000000,0.000000,0.381520,0.052519,0.150000
6,0.176471,0.391960,0.409836,0.323232,0.104019,0.461997,0.072588,0.083333
7,0.588235,0.577889,0.000000,0.000000,0.000000,0.526080,0.023911,0.133333
8,0.117647,0.989950,0.573770,0.454545,0.641844,0.454545,0.034159,0.533333
9,0.470588,0.628141,0.786885,0.000000,0.000000,0.000000,0.065756,0.550000
10,0.235294,0.552764,0.754098,0.000000,0.000000,0.560358,0.048249,0.150000
11,0.588235,0.844221,0.606557,0.000000,0.000000,0.566319,0.195986,0.216667
12,0.588235,0.698492,0.655738,0.000000,0.000000,0.403875,0.581981,0.600000
13,0.058824,0.949749,0.491803,0.232323,1.000000,0.448584,0.136635,0.633333
14,0.294118,0.834171,0.590164,0.191919,0.206856,0.384501,0.217336,0.500000
15,0.411765,0.502513,0.000000,0.000000,0.000000,0.447094,0.173356,0.183333
16,0.000000,0.592965,0.688525,0.474747,0.271868,0.682563,0.201964,0.166667
17,0.411765,0.537688,0.606557,0.000000,0.000000,0.441133,0.075149,0.166667
18,0.058824,0.517588,0.245902,0.383838,0.098109,0.645306,0.044833,0.200000
19,0.058824,0.577889,0.573770,0.303030,0.113475,0.515648,0.192570,0.183333
20,0.176471,0.633166,0.721311,0.414141,0.277778,0.585693,0.267293,0.100000
21,0.470588,0.497487,0.688525,0.000000,0.000000,0.527571,0.132365,0.483333
22,0.411765,0.984925,0.737705,0.000000,0.000000,0.593145,0.159266,0.333333
23,0.529412,0.597990,0.655738,0.353535,0.000000,0.432191,0.078992,0.133333
24,0.647059,0.718593,0.770492,0.333333,0.172577,0.545455,0.075149,0.500000
25,0.588235,0.628141,0.573770,0.262626,0.135934,0.463487,0.054227,0.333333
26,0.411765,0.738693,0.622951,0.000000,0.000000,0.587183,0.076430,0.366667
27,0.058824,0.487437,0.540984,0.151515,0.165485,0.345753,0.174637,0.016667
28,0.764706,0.728643,0.672131,0.191919,0.130024,0.330849,0.071307,0.600000
29,0.294118,0.587940,0.754098,0.000000,0.000000,0.508197,0.110589,0.283333
...,...,...,...,...,...,...,...,...
738,0.117647,0.497487,0.491803,0.171717,0.189125,0.545455,0.160120,0.000000
739,0.058824,0.512563,0.606557,0.000000,0.000000,0.588674,0.091802,0.350000
740,0.647059,0.603015,0.655738,0.373737,0.177305,0.630402,0.301879,0.450000
741,0.176471,0.512563,0.360656,0.202020,0.111111,0.459016,0.137489,0.083333
742,0.058824,0.547739,0.475410,0.181818,0.137116,0.424739,0.060205,0.016667
743,0.529412,0.703518,0.770492,0.000000,0.000000,0.487332,0.280102,0.400000
744,0.764706,0.768844,0.721311,0.373737,0.165485,0.605067,0.467976,0.300000
745,0.705882,0.502513,0.688525,0.333333,0.124113,0.447094,0.175064,0.416667
746,0.058824,0.738693,0.770492,0.414141,0.000000,0.734724,0.119556,0.100000
747,0.058824,0.407035,0.606557,0.414141,0.067376,0.690015,0.434671,0.183333
748,0.176471,0.939698,0.573770,0.222222,0.236407,0.542474,0.140905,0.250000
749,0.352941,0.814070,0.508197,0.000000,0.000000,0.362146,0.042699,0.483333
750,0.235294,0.683417,0.573770,0.000000,0.000000,0.464978,0.471392,0.016667
751,0.058824,0.608040,0.639344,0.393939,0.087470,0.581222,0.078138,0.116667
752,0.176471,0.542714,0.508197,0.242424,0.000000,0.387481,0.061913,0.066667
753,0.000000,0.909548,0.721311,0.444444,0.602837,0.645306,0.061486,0.083333
754,0.470588,0.773869,0.639344,0.323232,0.000000,0.482861,0.155850,0.400000
755,0.058824,0.643216,0.721311,0.393939,0.130024,0.543964,0.418019,0.266667
756,0.411765,0.688442,0.737705,0.414141,0.000000,0.476900,0.133646,0.300000
757,0.000000,0.618090,0.590164,0.000000,0.000000,0.540984,0.076857,0.516667
758,0.058824,0.532663,0.622951,0.000000,0.000000,0.558867,0.050811,0.083333
759,0.352941,0.954774,0.754098,0.000000,0.000000,0.529061,0.085397,0.750000
760,0.117647,0.442211,0.475410,0.262626,0.018913,0.423249,0.293766,0.016667
761,0.529412,0.854271,0.606557,0.313131,0.000000,0.655738,0.138770,0.366667
762,0.529412,0.447236,0.508197,0.000000,0.000000,0.335320,0.027327,0.200000
763,0.588235,0.507538,0.622951,0.484848,0.212766,0.490313,0.039710,0.700000
764,0.117647,0.613065,0.573770,0.272727,0.000000,0.548435,0.111870,0.100000
765,0.294118,0.608040,0.590164,0.232323,0.132388,0.390462,0.071307,0.150000
766,0.058824,0.633166,0.491803,0.000000,0.000000,0.448584,0.115713,0.433333
767,0.058824,0.467337,0.573770,0.313131,0.000000,0.453055,0.101196,0.033333

In [52]:
sfm = SelectFromModel(LogisticRegression())

In [53]:
sfm

SelectFromModel(estimator=LogisticRegression(C=1.0, class_weight=None,
                                             dual=False, fit_intercept=True,
                                             intercept_scaling=1, l1_ratio=None,
                                             max_iter=100, multi_class='warn',
                                             n_jobs=None, penalty='l2',
                                             random_state=None, solver='warn',
                                             tol=0.0001, verbose=0,
                                             warm_start=False),
                max_features=None, norm_order=1, prefit=False, threshold=None)

In [54]:
sfm.fit(_X_b,_y_b)

C:\Users\Ajay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

SelectFromModel(estimator=LogisticRegression(C=1.0, class_weight=None,
                                             dual=False, fit_intercept=True,
                                             intercept_scaling=1, l1_ratio=None,
                                             max_iter=100, multi_class='warn',
                                             n_jobs=None, penalty='l2',
                                             random_state=None, solver='warn',
                                             tol=0.0001, verbose=0,
                                             warm_start=False),
                max_features=None, norm_order=1, prefit=False, threshold=None)

In [55]:
sfm.get_support()

array([False,  True, False, False, False,  True, False, False])

In [56]:
list(_X_b)

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']

In [57]:
feature_6 = ['Glucose','BMI']